title: Shunya's home
views:

  - title: Overview
    icon: 'mdi:floor-plan'
    cards:
      - type: heading
        heading: Overview

  - title: Map
    icon: mdi:map
    type: panel
    cards:
      - type: map
        auto_fit: true
        show_all: true

  - title: Clean Up
    icon: 'mdi:robot-vacuum'
    cards:
      - type: grid
        cards:
          - type: custom:xiaomi-vacuum-map-card
            vacuum_platform: Xiaomi Miio
            entity: vacuum.dreamebot_d10_plus
            map_source:
              camera: camera.dreamebot_d10_plus_map
            calibration_source:
              camera: true
            map_modes:
              - template: vacuum_clean_zone
                max_selections: 10
                repeats_type: EXTERNAL
                max_repeats: 3
                service_call_schema:
                  service: dreame_vacuum.vacuum_clean_zone
                  service_data:
                    entity_id: '[[entity_id]]'
                    zone: '[[selection]]'
                    repeats: '[[repeats]]'
              - template: vacuum_clean_segment
                repeats_type: EXTERNAL
                max_repeats: 3
                service_call_schema:
                  service: dreame_vacuum.vacuum_clean_segment
                  service_data:
                    entity_id: '[[entity_id]]'
                    segments: '[[selection]]'
                    repeats: '[[repeats]]'
                predefined_selections:
                  - id: 1
                    outline:
                      - - -7050
                        - 5200
                      - - -7050
                        - 6150
                      - - -6750
                        - 6150
                      - - -6750
                        - 5200
                  - id: 2
                    outline:
                      - - -7000
                        - 650
                      - - -7000
                        - 2000
                      - - -5700
                        - 2000
                      - - -5700
                        - 650
                  - id: 3
                    outline:
                      - - -8550
                        - 5000
                      - - -8550
                        - 6050
                      - - -6950
                        - 6050
                      - - -6950
                        - 5000
                  - id: 4
                    outline:
                      - - -500
                        - -1050
                      - - -500
                        - 450
                      - - 2450
                        - 450
                      - - 2450
                        - -1050
                  - id: 6
                    outline:
                      - - -8300
                        - -850
                      - - -8300
                        - 700
                      - - -5650
                        - 700
                      - - -5650
                        - -850
                  - id: 7
                    outline:
                      - - -5700
                        - -1050
                      - - -5700
                        - 4800
                      - - -300
                        - 4800
                      - - -300
                        - -1050
                  - id: 8
                    outline:
                      - - -7000
                        - 1900
                      - - -7000
                        - 4800
                      - - -4750
                        - 4800
                      - - -4750
                        - 1900
                  - id: 9
                    outline:
                      - - -9150
                        - 650
                      - - -9150
                        - 5000
                      - - -6700
                        - 5000
                      - - -6700
                        - 650
              - name: Clean Spot
                icon: mdi:map-marker-plus
                max_repeats: 3
                selection_type: MANUAL_POINT
                repeats_type: EXTERNAL
                service_call_schema:
                  service: dreame_vacuum.vacuum_clean_spot
                  service_data:
                    entity_id: '[[entity_id]]'
                    points: '[[selection]]'
                    repeats: '[[repeats]]'
